# Generated by Django 5.2.1 on 2025-05-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
