# Generated by Django 5.2.1 on 2025-06-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_author_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='can_manage_articles',
            field=models.BooleanField(default=False, help_text='Bu yazarın makaleleri yönetme yetkisi'),
        ),
    ]
