# Generated by Django 5.2.1 on 2025-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_author_can_manage_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='can_manage_articles',
        ),
        migrations.AddField(
            model_name='author',
            name='editor_article',
            field=models.BooleanField(default=False, help_text='Bu yazarın editör yetkisi'),
        ),
    ]
