# Generated by Django 5.2.1 on 2025-05-20 13:55

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_alter_article_options_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=articles.models.article_file_upload_to, validators=[articles.models.validate_pdf]),
        ),
    ]
