# Generated by Django 5.2.1 on 2025-05-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_tag_article_downloads_article_likes_article_shares_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
