# Generated by Django 5.2.1 on 2025-06-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.TextField(blank=True, help_text='Anahtar kelimeleri virgülle ayırarak girin', null=True),
        ),
    ]
