# Generated by Django 5.2.1 on 2025-06-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0026_article_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
