# Generated by Django 5.2.1 on 2025-06-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_alter_category_options_category_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order']},
        ),
    ]
