# Generated by Django 5.2.1 on 2025-06-12 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
