# Generated by Django 5.2.1 on 2025-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_remove_article_isactive_article_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_admin_note_read_by_author',
            field=models.BooleanField(default=True),
        ),
    ]
