# Generated by Django 5.2.1 on 2025-06-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0034_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
