# Generated by Django 5.2.1 on 2025-06-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0035_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='İndirilme Sayısı'),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
    ]
