# Generated by Django 5.2.1 on 2025-06-14 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_article_download_count_article_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='download_count',
        ),
    ]
