# Generated by Django 5.2.1 on 2025-06-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_remove_article_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='view_count',
        ),
    ]
